blog/urls.py
# -*- coding: utf-8 -*-
"""blog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
import xadmin
from django.conf.urls import url
from users.views import IndexView, AboutView, BlogInputView, BlogsView, page_not_found, page_error
from articles.views import ArticleView
from tags.views import TagView
from classes.views import TypeView
from archives.views import ArchivesView
from settings import MEDIA_ROOT
from django.views.static import serve

# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^index/', IndexView.as_view(), name="index"),
    url(r'^$', IndexView.as_view(), name="index"),
    url(r"^tags/", TagView.as_view(), name="tags"),
    url(r"^types", TypeView.as_view(), name="types"),
    url(r"^archives", ArchivesView.as_view(), name="archives"),
    url(r"^about", AboutView.as_view(), name="about"),
    url(r'^blog/', ArticleView.as_view(), name="blog"),
    url(r"^issue", BlogInputView.as_view(), name="issue"),
    url(r"^admin", BlogsView.as_view(), name="admin"),

    # 配置上传函数
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]
# 全局404页面配置
handler404 = page_not_found
handler500 = page_error

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

apps/archives/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from articles.models import Article


# Create your models here.
class Archive(models.Model):
    time = models.CharField(max_length=100, verbose_name=u"时间")
    article = models.ForeignKey(Article, verbose_name=u"文章")

    class Meta:
        verbose_name = u"归档"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.time

apps/articles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import datetime
from django.db import models
from DjangoUeditor.models import UEditorField
from users.models import UserProfile
from tags.models import Tag
from classes.models import Type


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name=u"标题")
    guide = models.TextField(max_length=300, default=u"", verbose_name=u"引用")
    origin = models.CharField(max_length=100, choices=(("原创", "原创"), ("引用", "引用"), ("转载", "转载")), default=u"原创",
                              verbose_name=u"来源")
    content = UEditorField(imagePath="article/images/", width=1000, height=300,
                           filePath="article/files/", default='', verbose_name=u"内容")
    tag = models.ManyToManyField(Tag, verbose_name=u"标签")
    type = models.ForeignKey(Type, verbose_name=u"分类")
    image = models.ImageField(upload_to="article/images", default="article/images/default.jpg", verbose_name=u"图片")
    publisher = models.ForeignKey(UserProfile, verbose_name=u"发布者")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"发布时间")

    class Meta:
        verbose_name = u"文章"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

apps/tags/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name=u"名称")

    class Meta:
        verbose_name = u"标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/archives/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.views.generic.base import View
from articles.models import Article
from archives.models import Archive
from django.shortcuts import render


# Create your views here.
class ArchivesView(View):
    """归档"""

    def get(self, request):
        """取出博客信息"""
        # print (1/0)
        article = Article.objects.all()
        archives=Archive.objects.all()
        return render(request, 'archives.html', {
            "article": article,
            "archives": archives,
        })

apps/tags/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.views.generic.base import View
from articles.models import Article
from tags.models import Tag
from django.shortcuts import render


# Create your views here.
class TagView(View):
    """标签"""

    def get(self, request):
        """取出博客信息"""
        # print (1/0)
        article_list = Article.objects.all()
        recommend = Article.objects.all()[:10]
        tags = Tag.objects.all()[:8]
        paginator = Paginator(article_list, 5)
        page = request.GET.get('page')
        try:
            article = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            article = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            article = paginator.page(paginator.num_pages)
        return render(request, 'tags.html', {
            "article": article,
            "tags": tags,
            "recommends": recommend,
        })

templates/tags.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <mate name="viewport" content="width=device-width,initial-scale=1.0"/>
    <title>标签</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.css">
    <link rel="stylesheet" href="../static/css/animate.css">
    <link rel="stylesheet" href="../static/lib/tocbot/tocbot.css">
    <link rel="stylesheet" href="../static/css/me.css">
</head>

<body>
<!--导航-->
<nav class="ui inverted attached segment me-padded-tb-mini m-shadow-small">
    <div class="ui container">
        <div class="ui inverted secondary menu stackable  ">
            <h2 class="ui teal header item">Blog</h2>
            <a href="{% url 'index' %}" class="m-item item m-mobile-hide"><i class="home icon"></i>首页</a>
            <a href="{% url 'types' %}" class="m-item item m-mobile-hide"><i class="idea icon"></i>分类</a>
            <a href="{% url 'tags' %}" class="active animated pulse m-item item m-mobile-hide"><i class="tags icon"></i>标签</a>
            <a href="{% url 'archives' %}" class="m-item item m-mobile-hide"><i class="clone icon"></i>归档</a>
            <a href="{% url 'about' %}" class="m-item item m-mobile-hide"><i class="info icon"></i>关于我</a>
            <div class="right m-item item m-mobile-hide">
                <div class="ui icon inverted gray input">
                    <input type="text" placeholder="Search...">
                    <i class="search link icon"></i>
                </div>
            </div>
        </div>
    </div>
    <a href="#" class="ui black icon button m-right-top m-mobile-show menu toggle">
        <i class="icon sidebar"></i>
    </a>
</nav>

<!--中间内容-->
<div id="waypoint" class="me-padded-tb-big m-container animated fadeInUpBig">
    <div class="ui container">
        <!--标签数量header-->
        <div class="ui top attached segment">
            <div class="ui middle aligned two column grid">
                <div class="column">
                    <h3 class="ui teal header">标签</h3>
                </div>
                <div class="right aligned column">
                    共<h2 class="ui orange header m-inline-block m-text-thin">&nbsp; {{ tags.count }} &nbsp;</h2>个
                </div>
            </div>
        </div>
        <!--分类标签-->
        <div class="ui attached segment me-padded-tb-large">
            <div class="ui container">
                {%for tag in tags %}
                <a class="ui teal basic left pointing label m-margin-tb-tiny">
                    {{ tag.name }} <div class="detail">{{ tag.article_set.count }}</div>
                </a>
                {% endfor %}
            </div>
        </div>
        <!--正文列表-->
        <div class="ui top attached teal segment">
            {% for art in article %}
                <div class="ui padded vertical segment me-padded-tb-large m-mobile-clear">
                        <div class="ui mobile reversed stackable grid">
                            <!--左侧文字-->
                            <div class=" eleven wide column">
                                <!--标题-->
                                <h3 class="ui header">
                                    {{ art.title }}
                                </h3>
                                <!--内容-->
                                <p class="m-text">
                                    {% if art.guide|length >= 140 %}
                                    {{ art.guide|slice:"140"}}......
                                    {% else%}
                                        {{ art.guide }}
                                    {% endif %}
                                </p>
                                <!--文字标签-->
                                <div class="ui stackable grid">
                                    <div class="eleven wide column">
                                        <div class="ui mini link list horizontal">
                                            <!--用户信息（头像+用户名）-->
                                            <div class="item">
                                                <img src="https://picsum.photos/100/100/?image=1005" alt="" class="ui avatar image">
                                                <div class="content">
                                                    <a class="header">{{ art.publisher.name }}</a>
                                                </div>
                                            </div>
                                            <!--发布时间-->
                                            <div class="item">
                                                <i class="calendar icon"></i>{{ art.add_time }}
                                            </div>
                                            <!--浏览次数-->
                                            <div class="item">
                                                <i class="eye icon"></i>2312
                                            </div>
                                        </div>
                                    </div>
                                    <!--标签-->
                                    <div class="right aligned five wide column">
                                        <a href="#" target="_blank" class="ui orange basic label  me-padded-tiny m-text-thin">{{ art.type }}</a>
                                    </div>
                                </div>

                            <!--标签-->
                            {% if art.tag.count > 0 %}
                                    <div class="m-margin-top ">
                                    {% for t in art.tag.values %}
                                        <a href="#" target="_blank" class="ui teal basic label me-padded-tiny m-text-thin">{{ t.name }}</a>
                                    {% endfor %}
                                    </div>
                                    {% endif %}
                            </div>
                            <!--右侧图片-->
                            <div class="five wide column">
                                <a href="#" target="_blank">
                                    <h3></h3>
                                    <br>
                                    <img src="{{ art.image.url}}" alt="" class="ui rounded image" style="width: 18em;height:10em ">
                                </a>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
        <!--分页-->
        <div class="ui bottom attached segment">
                    <div class="ui middle aligned two column grid">
                        {% if article.has_previous %}
                            <div class="column">
                                <a href="?page={{ article.previous_page_number }}" class="ui teal basic mini button" style="margin-left: 160px">上一页</a>
                            </div>
                        {% elif article.has_next %}
                            <div class="middle aligned column">

                            </div>
                             <div class="right aligned column">
                                <a href="?page={{ article.next_page_number }}" class="ui teal basic mini button" style="margin-right: 160px">下一页</a>
                             </div>
                        {% else %}
                            <div class="column">
                                <a href="?page={{ article.previous_page_number }}" class="ui teal basic mini button" style="margin-left: 160px">上一页</a>
                            </div>
                            <div class="right aligned column">
                                <a href="?page={{ article.next_page_number }}" class="ui teal basic mini button" style="margin-right: 160px">下一页</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
    </div>
</div>
<!--右下角悬浮菜单-->
<div id="toolbar" class="me-padded m-fixed m-right-bottom " style="display: none" >
    <div class="ui vertical icon buttons">
        <div id="toTop-button" class="ui button icon"><i class="chevron up icon"></i></div>
        <button type="button" class="ui m-item-float m-mobile-hide wechat icon button"><i class="weixin icon"></i></button>
        <div class="ui button menu float m-mobile-show icon"><i class="chevron down icon"></i></div>
    </div>
</div>
<!--微信二维码-->
<div id="qrcode" class="ui flowing popup transition hidden wechat-show" style="width: 130px">
    <!--img src="./static/images/wechat.jpg" alt="" class="ui rounded image" width="120px"-->
</div>
<!--底部footer-->
<footer class="ui inverted vertical segment me-padded-tb-massive">
    <div class="ui center aligned container">
        <!--分成4个格子-->
        <div class="ui  inverted divided stackable grid">
            <!--图片格子-->
            <div class="three wide column">
                <div class="ui inverted link list">
                    <div class="item">
                        <img src="static/images/wechat.jpg" class="ui rounded image" alt="" style="width: 110px">
                    </div>
                </div>
            </div>
            <!--博客格子-->
            <div class="three wide column">
                <h4 class="ui inverted header m-text-thin m-text-spaced">
                    最新博客
                </h4>
                <div class="ui inverted link list">
                    <a href="#" class="item">PHP Storm（安装指南）</a>
                    <a href="#" class="item">Intellij IDEA</a>
                    <a href="#" class="item">eclipse SDK（配置方式）</a>
                </div>
            </div>
            <!--联系我格子-->
            <div class="three wide column">
                <h4 class="ui inverted header m-text-thin m-text-spaced">
                    联系我
                </h4>
                <div class="ui inverted link list">
                    <a href="#" class="item">Email:466390825@qq.com</a>
                    <a href="#" class="item">QQ:466390825</a>
                    <a href="#" class="item">Wechat:minmo12_13</a>
                </div>
            </div>
            <!--说明格子-->
            <div class="seven wide column">
                <h4 class="ui inverted header m-text-thin m-text-spaced">
                    博客说明
                </h4>
                <p class="m-text-thin m-text-spaced m-opacity-mini">
                    这是一个个人博客，用于记录个人编程相关问题和日志。
                </p>
            </div>
        </div>
        <!--底部版权声明-->
        <div class="ui inverted section divider"></div>
        <p class="m-text-thin m-text-spaced m-opacity-tiny">
            Copyright © 2018 - 2019 Blog Designed by Zhenyanxin
        </p>
    </div>
</footer>
<!--jquery和semantic引用-->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.2/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.js"></script>
<script src="../static/lib/tocbot/tocbot.min.js"></script>
<script src="../static/lib/tocbot/tocbot.js"></script>
<script src="../static/lib/qrcode/qrcode.js"></script>
<script src="../static/lib/qrcode/qrcode.min.js"></script>
<script src="../static/js/jquery.scrollTo.min.js"></script>
<script src="../static/lib/waypoints/jquery.waypoints.js"></script>
<script src="../static/lib/waypoints/jquery.waypoints.min.js"></script>
<script>
    //tocbot初始化
    tocbot.init({
        // Where to render the table of contents.
        tocSelector: '.js-toc',
        // Where to grab the headings to build the table of contents.
        contentSelector: '.js-toc-content',
        // Which headings to grab inside of the contentSelector element.
        headingSelector: 'h1, h2, h3',
    });
    $('.menu.toggle').click(function () {
        $('.m-item').toggleClass('m-mobile-hide');
    });
    //悬浮隐藏
    $('.menu.float').click(function () {
        $('.m-item-float').toggleClass('m-mobile-hide');
    });
    //悬浮微信按钮
    $('.wechat').popup({
        popup:$('.wechat-show.popup'),
        position:'left center'
    });
    //自动生成二维码
    var qrcode = new QRCode("qrcode", {
        text: "www.baidu.com",
        width: 110,
        height: 110,
        colorDark : "#000000",
        colorLight : "#ffffff",
        correctLevel : QRCode.CorrectLevel.H
    });
    //到顶上
    $('#toTop-button').click(function () {
        $(window).scrollTo(0,1000)
    });
    //指定位置出现悬浮
    var waypoint = new Waypoint({
        element: document.getElementById('waypoint'),
        handler: function(direction) {
            if(direction=='down'){
                $('#toolbar').show();
            }else {
                $('#toolbar').hide(500);
            }
        }
    })
</script>
</body>
</html>

templates/types.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <mate name="viewport" content="width=device-width,initial-scale=1.0"/>
    <title>分类</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.css">
    <link rel="stylesheet" href="../static/css/animate.css">
    <link rel="stylesheet" href="../static/lib/tocbot/tocbot.css">
    <link rel="stylesheet" href="../static/css/me.css">
</head>

<body>
<!--导航-->
<nav class="ui inverted attached segment me-padded-tb-mini m-shadow-small">
    <div class="ui container">
        <div class="ui inverted secondary menu stackable  ">
            <h2 class="ui teal header item">Blog</h2>
            <a href="index" class="m-item item m-mobile-hide"><i class="home icon"></i>首页</a>
            <a href="types" class="active animated pulse m-item item m-mobile-hide"><i class="idea icon"></i>分类</a>
            <a href="tags" class="m-item item m-mobile-hide"><i class="tags icon"></i>标签</a>
            <a href="archives" class="m-item item m-mobile-hide"><i class="clone icon"></i>归档</a>
            <a href="about" class="m-item item m-mobile-hide"><i class="info icon"></i>关于我</a>
            <div class="right m-item item m-mobile-hide">
                <div class="ui icon inverted gray input">
                    <input type="text" placeholder="Search...">
                    <i class="search link icon"></i>
                </div>
            </div>
        </div>
    </div>
    <a href="#" class="ui black icon button m-right-top m-mobile-show menu toggle">
        <i class="icon sidebar"></i>
    </a>
</nav>

<!--中间内容-->
<div id="waypoint" class="me-padded-tb-big m-container animated fadeInUpBig">
    <div class="ui container">
        <!--分类数量header-->
        <div class="ui top attached segment">
            <div class="ui middle aligned two column grid">
                <div class="column">
                    <h3 class="ui teal header">分类</h3>
                </div>
                <div class="right aligned column">
                    共<h2 class="ui orange header m-inline-block m-text-thin">&nbsp; {{ types.count }} &nbsp;</h2>个
                </div>
            </div>
        </div>
        <!--分类标签-->
        <div class="ui attached segment me-padded-tb-large">
            <div class="ui container">
                {% for type in types %}
                <div class="ui labeled button m-margin-tb-tiny">
                    <a href="#" class="ui basic teal button">{{ type.name }}</a>
                    <div class="ui basic teal left pointing label">{{ type.article_set.count }}</div>
                </div>
                {% endfor %}
            </div>
        </div><!--正文列表-->
        <div class="ui top attached teal segment">
            {% for art in article %}
                <div class="ui padded vertical segment me-padded-tb-large m-mobile-clear">
                        <div class="ui mobile reversed stackable grid">
                            <!--左侧文字-->
                            <div class=" eleven wide column">
                                <!--标题-->
                                <h3 class="ui header">
                                    {{ art.title }}
                                </h3>
                                <!--内容-->
                                <p class="m-text">
                                    {% if art.guide|length >= 140 %}
                                    {{ art.guide|slice:"140"}}......
                                    {% else%}
                                        {{ art.guide }}
                                    {% endif %}
                                </p>
                                <!--文字标签-->
                                <div class="ui stackable grid">
                                    <div class="eleven wide column">
                                        <div class="ui mini link list horizontal">
                                            <!--用户信息（头像+用户名）-->
                                            <div class="item">
                                                <img src="https://picsum.photos/100/100/?image=1005" alt="" class="ui avatar image">
                                                <div class="content">
                                                    <a class="header">{{ art.publisher.name }}</a>
                                                </div>
                                            </div>
                                            <!--发布时间-->
                                            <div class="item">
                                                <i class="calendar icon"></i>{{ art.add_time }}
                                            </div>
                                            <!--浏览次数-->
                                            <div class="item">
                                                <i class="eye icon"></i>2312
                                            </div>
                                        </div>
                                    </div>
                                    <!--标签-->
                                    <div class="right aligned five wide column">
                                        <a href="#" target="_blank" class="ui orange basic label  me-padded-tiny m-text-thin">{{ art.type }}</a>
                                    </div>
                                </div>

                            <!--标签-->
                            {% if art.tag.count > 0 %}
                                    <div class="m-margin-top ">
                                    {% for t in art.tag.values %}
                                        <a href="#" target="_blank" class="ui teal basic label me-padded-tiny m-text-thin">{{ t.name }}</a>
                                    {% endfor %}
                                    </div>
                                    {% endif %}
                            </div>
                            <!--右侧图片-->
                            <div class="five wide column">
                                <a href="#" target="_blank">
                                    <h3></h3>
                                    <br>
                                    <img src="{{ art.image.url}}" alt="" class="ui rounded image" style="width: 18em;height:10em ">
                                </a>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
        <!--分页-->
        <div class="ui bottom attached segment">
                    <div class="ui middle aligned two column grid">
                        {% if article.has_previous %}
                            <div class="column">
                                <a href="?page={{ article.previous_page_number }}" class="ui teal basic mini button" style="margin-left: 160px">上一页</a>
                            </div>
                        {% elif article.has_next %}
                            <div class="middle aligned column">

                            </div>
                             <div class="right aligned column">
                                <a href="?page={{ article.next_page_number }}" class="ui teal basic mini button" style="margin-right: 160px">下一页</a>
                             </div>
                        {% else %}
                            <div class="column">
                                <a href="?page={{ article.previous_page_number }}" class="ui teal basic mini button" style="margin-left: 160px">上一页</a>
                            </div>
                            <div class="right aligned column">
                                <a href="?page={{ article.next_page_number }}" class="ui teal basic mini button" style="margin-right: 160px">下一页</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
    </div>
</div>
<!--右下角悬浮菜单-->
<div id="toolbar" class="me-padded m-fixed m-right-bottom " style="display: none" >
    <div class="ui vertical icon buttons">
        <div id="toTop-button" class="ui button icon"><i class="chevron up icon"></i></div>
        <button type="button" class="ui m-item-float m-mobile-hide wechat icon button"><i class="weixin icon"></i></button>
        <div class="ui button menu float m-mobile-show icon"><i class="chevron down icon"></i></div>
    </div>
</div>
<!--微信二维码-->
<div id="qrcode" class="ui flowing popup transition hidden wechat-show" style="width: 130px">
    <!--img src="./static/images/wechat.jpg" alt="" class="ui rounded image" width="120px"-->
</div>
<!--底部footer-->
<footer class="ui inverted vertical segment me-padded-tb-massive">
    <div class="ui center aligned container">
        <!--分成4个格子-->
        <div class="ui  inverted divided stackable grid">
            <!--图片格子-->
            <div class="three wide column">
                <div class="ui inverted link list">
                    <div class="item">
                        <img src="static/images/wechat.jpg" class="ui rounded image" alt="" style="width: 110px">
                    </div>
                </div>
            </div>
            <!--博客格子-->
            <div class="three wide column">
                <h4 class="ui inverted header m-text-thin m-text-spaced">
                    最新博客
                </h4>
                <div class="ui inverted link list">
                    <a href="#" class="item">PHP Storm（安装指南）</a>
                    <a href="#" class="item">Intellij IDEA</a>
                    <a href="#" class="item">eclipse SDK（配置方式）</a>
                </div>
            </div>
            <!--联系我格子-->
            <div class="three wide column">
                <h4 class="ui inverted header m-text-thin m-text-spaced">
                    联系我
                </h4>
                <div class="ui inverted link list">
                    <a href="#" class="item">Email:466390825@qq.com</a>
                    <a href="#" class="item">QQ:466390825</a>
                    <a href="#" class="item">Wechat:minmo12_13</a>
                </div>
            </div>
            <!--说明格子-->
            <div class="seven wide column">
                <h4 class="ui inverted header m-text-thin m-text-spaced">
                    博客说明
                </h4>
                <p class="m-text-thin m-text-spaced m-opacity-mini">
                    这是一个个人博客，用于记录个人编程相关问题和日志。
                </p>
            </div>
        </div>
        <!--底部版权声明-->
        <div class="ui inverted section divider"></div>
        <p class="m-text-thin m-text-spaced m-opacity-tiny">
            Copyright © 2018 - 2019 Blog Designed by Zhenyanxin
        </p>
    </div>
</footer>
<!--jquery和semantic引用-->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.2/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.js"></script>
<scrip
        t src="../static/lib/tocbot/tocbot.min.js"></script>
<script src="../static/lib/tocbot/tocbot.js"></script>
<script src="../static/lib/qrcode/qrcode.js"></script>
<script src="../static/lib/qrcode/qrcode.min.js"></script>
<script src="../static/js/jquery.scrollTo.min.js"></script>
<script src="../static/lib/waypoints/jquery.waypoints.js"></script>
<script src="../static/lib/waypoints/jquery.waypoints.min.js"></script>
<script>
    //tocbot初始化
    tocbot.init({
        // Where to render the table of contents.
        tocSelector: '.js-toc',
        // Where to grab the headings to build the table of contents.
        contentSelector: '.js-toc-content',
        // Which headings to grab inside of the contentSelector element.
        headingSelector: 'h1, h2, h3',
    });
    $('.menu.toggle').click(function () {
        $('.m-item').toggleClass('m-mobile-hide');
    });
    //悬浮隐藏
    $('.menu.float').click(function () {
        $('.m-item-float').toggleClass('m-mobile-hide');
    });
    //悬浮微信按钮
    $('.wechat').popup({
        popup:$('.wechat-show.popup'),
        position:'left center'
    });
    //自动生成二维码
    var qrcode = new QRCode("qrcode", {
        text: "www.baidu.com",
        width: 110,
        height: 110,
        colorDark : "#000000",
        colorLight : "#ffffff",
        correctLevel : QRCode.CorrectLevel.H
    });
    //到顶上
    $('#toTop-button').click(function () {
        $(window).scrollTo(0,1000)
    });
    //指定位置出现悬浮
    var waypoint = new Waypoint({
        element: document.getElementById('waypoint'),
        handler: function(direction) {
            if(direction=='down'){
                $('#toolbar').show();
            }else {
                $('#toolbar').hide(500);
            }
        }
    })
</script>
</body>
</html>